# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao da atividade')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, max_length=256, verbose_name='descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor')),
                ('tipo_evento', models.CharField(blank=True, choices=[('<bound method EscolhaEnum.value of <TipoEvento.congresso: 0>>', 'congresso'), ('<bound method EscolhaEnum.value of <TipoEvento.semana: 1>>', 'semana'), ('<bound method EscolhaEnum.value of <TipoEvento.seminario: 2>>', 'seminario')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacionamento', models.TextField(blank=True, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('tipo_de_relacionamento', models.TextField(blank=True, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=30, verbose_name='Tag')),
                ('tag_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_evento', to='core.Evento', verbose_name='tags evento')),
            ],
        ),
    ]
