# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='instituicao_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento'),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instituicao'),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='instituicao_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicoes_relacionadas', to='core.Evento', verbose_name='Instituicoes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=models.ManyToManyField(related_name='tags_do_evento', through='core.Tag_Evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.Evento', verbose_name='atividades'),
        ),
    ]
