# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='nome')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='valor')),
            ],
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='evento_instituicao',
            options={'verbose_name': 'Relacionamento_Instituicao_Evento', 'verbose_name_plural': 'Relacionamentos_Instituicao_Evento'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituicao', 'verbose_name_plural': 'Instituicoes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tag_evento',
            options={'verbose_name': 'Relacionamento_Tag_Evento', 'verbose_name_plural': 'Relacionamentos_Tag_Tag'},
        ),
        migrations.AlterModelOptions(
            name='tag_usuario',
            options={'verbose_name': 'Relacionamento_Tag_Usuario', 'verbose_name_plural': 'Relacionamentos_Tag_Usuario'},
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='tipo_de_relacionamento',
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_atividade', to='core.Evento', verbose_name='atividades'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='utils.Periodo', verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='evento',
            name='eventos_satelite',
            field=models.ManyToManyField(related_name='evento_satelite', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags_do_evento',
            field=models.ManyToManyField(related_name='tags_do_evento', through='core.Tag_Evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='evento_relacionado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='core.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_instituicao', to='core.Instituicao', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='tag_usuario',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento_instituicao',
            name='tipo_relacionamento',
            field=models.TextField(blank=True, default='', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(default='', max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='tag_usuario',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_trilha', to='core.Evento', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trilha',
            field=models.ManyToManyField(related_name='trilha', to='core.Trilha', verbose_name='trilha'),
        ),
    ]
