# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('utils', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhainscricao',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_trilha_Inscricao', to='user.Inscricao', verbose_name='trilha_incricao'),
        ),
        migrations.AddField(
            model_name='trilhainscricao',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilha_Inscricao', to='core.Trilha', verbose_name='trilha_inscricao'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='atividades',
            field=models.ManyToManyField(related_name='atividade_trilha', through='core.AtividadeTrilha', to='core.AtividadeAbstrata'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_trilha', to='core.Evento', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='responsaveis',
            field=models.ManyToManyField(related_name='responsavel_trilha', through='core.ResponsavelTrilha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag_usuario',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='tag_usuario',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='responsaveltrilha',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsavel_trilha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsaveltrilha',
            name='trilha',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trilha_dirigida', to='core.Trilha'),
        ),
        migrations.AddField(
            model_name='responsavelatividade',
            name='atividade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividade_dirigida', to='core.AtividadeAbstrata'),
        ),
        migrations.AddField(
            model_name='gerenciaevento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_gerente', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='gerenciaevento',
            name='gerente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventosatelite',
            name='eventos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_satelite', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='eventoinstituicao',
            name='evento_relacionado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='core.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='eventoinstituicao',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_instituicao', to='core.Instituicao', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_do_evento', to='utils.Endereco'),
        ),
        migrations.AddField(
            model_name='evento',
            name='gerentes',
            field=models.ManyToManyField(related_name='gerentes_do_evento', through='core.GerenciaEvento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodo_do_evento', to='utils.Periodo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags_do_evento',
            field=models.ManyToManyField(related_name='tags_do_evento', through='core.Tag_Evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='atividade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='espaco_da_atividade', to='core.AtividadeAbstrata'),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='espaco_do_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='atividadetrilha',
            name='atividade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividades_de_trilha', to='core.AtividadeAbstrata'),
        ),
        migrations.AddField(
            model_name='atividadetrilha',
            name='trilha',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_de_atividade', to='core.Trilha'),
        ),
        migrations.AddField(
            model_name='atividadeabstrata',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_myapp.mymodel_set+', to='core.Evento', verbose_name='atividades'),
        ),
        migrations.AddField(
            model_name='atividadeabstrata',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='utils.Periodo', verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='atividadeabstrata',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.atividadeabstrata_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='atividadeabstrata',
            name='trilhas',
            field=models.ManyToManyField(related_name='trilha_atividade', through='core.AtividadeTrilha', to='core.Trilha'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_atividade_simples', to='utils.Horario'),
        ),
    ]
