# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_usuario',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='tag_evento',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='gerenciaevento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_gerente', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='gerenciaevento',
            name='gerente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='evento_relacionado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='core.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_instituicao', to='core.Instituicao', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='evento',
            name='eventos_satelite',
            field=models.ManyToManyField(related_name='evento_satelite', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='gerentes',
            field=models.ManyToManyField(related_name='gerentes_do_evento', to='core.GerenciaEvento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags_do_evento',
            field=models.ManyToManyField(related_name='tags_do_evento', through='core.Tag_Evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.Evento', verbose_name='atividades'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='utils.Periodo', verbose_name='periodo'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trilha',
            field=models.ManyToManyField(related_name='trilha', to='core.Trilha', verbose_name='trilha'),
        ),
    ]
