# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 03:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagusuario',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagevento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='tagevento',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='responsaveltrilha',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsavel_trilha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavelatividade',
            name='atividade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividade_dirigida', to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='pacoteinscricao',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao_pacote_Inscricao', to='user.Inscricao', verbose_name='pacote_incricao'),
        ),
        migrations.AddField(
            model_name='pacoteinscricao',
            name='pacote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacote_Inscricao', to='core.Pacote', verbose_name='trilha_inscricao'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='atividades',
            field=models.ManyToManyField(related_name='atividade_trilha', through='core.AtividadePacote', to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_myapp.mymodel_set+', to='core.Evento', verbose_name='pacote'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.pacote_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='gerenciaevento',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_gerente', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='gerenciaevento',
            name='gerente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventosatelite',
            name='eventos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_satelite', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='eventoinstituicao',
            name='evento_relacionado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='core.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='eventoinstituicao',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='evento_instituicao', to='core.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_do_evento', to='utils.Endereco'),
        ),
        migrations.AddField(
            model_name='evento',
            name='gerentes',
            field=models.ManyToManyField(related_name='gerentes_do_evento', through='core.GerenciaEvento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodo_do_evento', to='utils.Periodo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='periodo_de_inscricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_evento', to='utils.Periodo'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags_do_evento',
            field=models.ManyToManyField(related_name='tags_do_evento', through='core.TagEvento', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='espacofisico',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='espaco_do_evento', to='core.Evento'),
        ),
        migrations.AddField(
            model_name='atividadepacote',
            name='atividade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividades_de_pacote', to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='atividadepacote',
            name='pacote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pacote_de_atividade', to='core.Pacote'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='espaco_fisico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espaco_atividade', to='core.EspacoFisico'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_myapp.mymodel_set+', to='core.Evento', verbose_name='atividades'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.HorarioAtividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.atividade_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trilhas',
            field=models.ManyToManyField(related_name='pacote_atividade', through='core.AtividadePacote', to='core.Pacote'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='responsaveis',
            field=models.ManyToManyField(related_name='responsavel_trilha', through='core.ResponsavelTrilha', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsaveltrilha',
            name='trilha',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trilha_dirigida', to='core.Trilha'),
        ),
    ]
