# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:40
from __future__ import unicode_literals

import core.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170805_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=enumfields.fields.EnumField(default='padrao', enum=core.models.TipoEvento, max_length=25),
        ),
        migrations.AlterField(
            model_name='gerenciaevento',
            name='tipo_gerente',
            field=enumfields.fields.EnumField(default='padrao', enum=core.models.TipoGerenciaEvento, max_length=25),
        ),
    ]
