# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170731_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='evento_instituicao',
            options={'verbose_name': 'Relacionamento_Instituicao_Evento', 'verbose_name_plural': 'Relacionamentos_Instituicao_Evento'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituicao', 'verbose_name_plural': 'Instituicoes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='tag_evento',
            options={'verbose_name': 'Relacionamento_Tag_Evento', 'verbose_name_plural': 'Relacionamentos_Tag_Tag'},
        ),
        migrations.AlterModelOptions(
            name='tag_usuario',
            options={'verbose_name': 'Relacionamento_Tag_Usuario', 'verbose_name_plural': 'Relacionamentos_Tag_Usuario'},
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='tags',
            new_name='tags_do_evento',
        ),
        migrations.RemoveField(
            model_name='evento_instituicao',
            name='instituicao_relacionada',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='instituicao_relacionada',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='tipo_de_relacionamento',
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='evento_relacionado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='core.Evento', verbose_name='Evento'),
        ),
    ]
