# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170805_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento_instituicao',
            name='tipo_relacionamento',
            field=models.CharField(default='', max_length=40, verbose_name='tipo'),
        ),
    ]
