# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170810_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='trilhas',
            field=models.ManyToManyField(default='Padrão', related_name='trilha_atividade', through='core.AtividadeTrilha', to='core.Trilha'),
        ),
    ]
