# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170801_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_instituicao',
            name='instituicao_relacionada',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='instituicao_relacionada',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='tipo_de_relacionamento',
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='evento_relacionado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='core.Evento', verbose_name='Evento'),
        ),
    ]
