# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170807_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='valor'),
        ),
    ]
