# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170729_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Evento')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_evento', to='core.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='tag_usuario',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='tag_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_de_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=models.ManyToManyField(related_name='tags_do_evento', through='core.Tag_Evento', to='core.Tag'),
        ),
    ]
