# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170805_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gerente', models.CharField(max_length=1)),
                ('gerente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='gerentes',
            field=models.ManyToManyField(related_name='gerentes_do_evento', to='core.GerenciaEvento'),
        ),
    ]
