# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170801_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo_evento',
        ),
    ]
