# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170807_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='valor'),
        ),
    ]
