# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evento_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(blank=True, choices=[('<bound method EscolhaEnum.value of <TipoEvento.congresso: 0>>', 'congresso'), ('<bound method EscolhaEnum.value of <TipoEvento.semana: 1>>', 'semana'), ('<bound method EscolhaEnum.value of <TipoEvento.seminario: 2>>', 'seminario')], max_length=1),
        ),
    ]
