# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170807_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='periodo',
            field=models.DateTimeField(default=''),
        ),
    ]
