# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('codigo_do_cupom', models.CharField(blank=True, max_length=100, verbose_name='cupom')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('status_pagamento', models.BooleanField(default=True, verbose_name='Pago/Não Pago')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.Periodo')),
            ],
        ),
    ]
