# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('descricao', models.TextField(blank=True, verbose_name='Descricao da atividade')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.Periodo')),
                ('valor_da_atividade', models.DecimalField(decimal_places=2,default=0, max_digits=5, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao do evento')),
                ('administrador_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario', verbose_name='Administrador')),
                ('atividades_diponiveis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_disponiveis', to='usuario.Inscricao')),
                ('meus_eventos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacionamento', models.TextField(blank=True, verbose_name='Tipo Relacionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome da instituiçao')),
                ('tipo_de_relacionamento', models.TextField(blank=True, verbose_name='tipo_de_relacionamento')),
                ('instituicao_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=30, verbose_name='Tag')),
                ('tag_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_evento', to='core.Evento', verbose_name='tags_evento')),
                ('tag_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_usuario', to='usuario.Usuario', verbose_name='tags_interesse')),
            ],
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instituicao'),
        ),
        migrations.AddField(
            model_name='evento_instituicao',
            name='instituicao_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instituicoes_relacionadas', to='core.Evento', verbose_name='Instituicoes'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='atividades_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Atividades_do_evento', to='core.Evento', verbose_name='Atividades'),
        ),
    ]