# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao da atividade')),
                ('valor_da_atividade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('descricao', models.TextField(blank=True, verbose_name='Descricao do evento')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.Periodo')),
            ],
        ),
    ]
