# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='atividades_evento',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='valor_da_atividade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='administrador_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='atividades_diponiveis',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='meus_eventos',
        ),
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.Evento', verbose_name='atividades'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='nome',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='valor'),
        ),
        migrations.AddField(
            model_name='evento',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to=settings.AUTH_USER_MODEL, verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(blank=True, choices=[('<bound method EscolhaEnum.value of <TipoEvento.congresso: 0>>', 'congresso'), ('<bound method EscolhaEnum.value of <TipoEvento.semana: 1>>', 'semana'), ('<bound method EscolhaEnum.value of <TipoEvento.seminario: 2>>', 'seminario')], max_length=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descricao da atividade'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, max_length=256, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='evento_instituicao',
            name='instituicao_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicoes_relacionadas', to='core.Evento', verbose_name='Instituicoes'),
        ),
        migrations.AlterField(
            model_name='evento_instituicao',
            name='tipo_relacionamento',
            field=models.TextField(blank=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='tipo_de_relacionamento',
            field=models.TextField(blank=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_evento', to='core.Evento', verbose_name='tags evento'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_interesse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_usuario', to=settings.AUTH_USER_MODEL, verbose_name='tags interesse'),
        ),
    ]
