# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='administrador_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario', verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='evento',
            name='meus_eventos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_eventos', to='usuario.Usuario'),
        ),
    ]
