# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170727_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='nome_tag',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_evento',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_interesse',
        ),
        migrations.AddField(
            model_name='tag_usuario',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacao', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='tag_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associcao', to=settings.AUTH_USER_MODEL),
        ),
    ]
