# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_inscricao', models.BooleanField(default=True, verbose_name='Inscrito/Não Inscrito')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nome do Usuário')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='minhas_incricoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_incricoes', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_inscricoes', to='usuario.Usuario', verbose_name='Usuario'),
        ),
    ]
