# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_inscricao', models.BooleanField(default=True, verbose_name='Inscrito/Não Inscrito')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Evento', verbose_name='Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_inscricoes', to='usuario.Usuario', verbose_name='Usuario'),
        ),
    ]
