# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170729_0909'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tags',
            field=models.ManyToManyField(related_name='Tags', through='core.Tag_Usuario', to='core.Tag'),
        ),
    ]
