# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('codigo_do_cupom', models.CharField(blank=True, max_length=100, verbose_name='cupom')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.Periodo')),
                ('lista_de_cupons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meus_cupons', to='core.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('status_pagamento', models.BooleanField(default=True, verbose_name='Pago/Não Pago')),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utils.Periodo')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor pagamento')),
            ],
        ),
    ]
