# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_auto_20170906_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='inscricao',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='de_incricao', to='user.Inscricao'),
        ),
    ]
