# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170801_1456'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Id de Inscricao', 'verbose_name_plural': 'Id das Inscricoes'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'O nome do user so pode conter letras, digitos ou osseguintes caracteres @/./+/-/_invalid')], verbose_name='Nome do Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='iteminscricao',
            unique_together=set([('atividade', 'inscricao')]),
        ),
    ]
