# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminscricao',
            name='atividade',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='iteminscricao',
            name='checkin',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.CheckinItemInscricao'),
        ),
        migrations.AddField(
            model_name='iteminscricao',
            name='inscricao',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='user.Inscricao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='atividades',
            field=models.ManyToManyField(through='user.ItemInscricao', to='core.Atividade'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='trilhas',
            field=models.ManyToManyField(through='core.TrilhaInscricao', to='core.Trilha'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='checkiniteminscricao',
            name='gerente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='gerente_chekin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tags',
            field=models.ManyToManyField(related_name='tags_do_usuario', through='core.Tag_Usuario', to='core.Tag'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
