# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170801_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminscricao',
            name='inscricao',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='user.Inscricao'),
        ),
    ]
