# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.TextField()),
                ('cidade', models.TextField()),
                ('bairro', models.TextField()),
                ('logradouro', models.TextField(blank=True)),
                ('numero', models.TextField()),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(re.compile('^\\d{8}$|^\\d{5}-\\d{3}$', 32), code='invalid', message='Informe um cep valido no formato 88888888 ou 88888-888')])),
                ('estado', models.TextField()),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data inicio')),
                ('hora_inicio', models.TimeField(blank=True, verbose_name='Hora inicio')),
                ('hora_fim', models.TimeField(blank=True, verbose_name='Hora Fim')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='HorarioAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data inicio')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fim', models.TimeField(verbose_name='Hora Fim')),
            ],
        ),
        migrations.CreateModel(
            name='MsgSimples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atual', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Observado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Observador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, verbose_name='Data inicio')),
                ('data_fim', models.DateField(blank=True, verbose_name='Data fim')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='HorarioAtividadeContinua',
            fields=[
                ('horario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.Horario')),
                ('atividade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Atividade', to='core.AtividadeContinua', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Horario_da_atividdade',
                'verbose_name_plural': 'Horarios_da_ativiade ',
            },
            bases=('utils.horario',),
        ),
        migrations.CreateModel(
            name='MsgCompleta',
            fields=[
                ('msgsimples_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.MsgSimples')),
                ('data', models.DateTimeField()),
                ('anterior', models.TextField(default='')),
            ],
            bases=('utils.msgsimples',),
        ),
        migrations.CreateModel(
            name='Notificador',
            fields=[
                ('observador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.Observador')),
            ],
            options={
                'verbose_name': 'Notificador',
                'verbose_name_plural': 'notificadores ',
            },
            bases=('utils.observador',),
        ),
        migrations.AddField(
            model_name='observador',
            name='observado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Observador', to='utils.Observador', verbose_name='Observador'),
        ),
    ]
