# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='data_fim',
            field=models.DateField(blank=True, verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='data_inicio',
            field=models.DateField(blank=True, verbose_name='Data inicio'),
        ),
    ]
