# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170805_1353'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Data inicio')),
                ('hora_inicio', models.TimeField(blank=True, verbose_name='Hora inicio')),
                ('hora_fim', models.TimeField(blank=True, verbose_name='Hora Fim')),
                ('atividade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Atividade', to='core.Atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Horario_da_atividdade',
                'verbose_name_plural': 'Horarios_da_ativiade ',
            },
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
    ]
