# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20170801_1456'),
        ('utils', '0002_auto_20170801_0157'),
    ]

    operations = [
    ]
